### PR TITLE
Purge queue in `sample` rather than `testEnded`

### PR DESCRIPTION
**Pull request by t-h-e**
`testEnded` does not work as a new instance of AMQPConsumer is created
and the channel is not set (NullPointerException).
Additionally, the queue should be purged at the point of the test plan
where the consumer is and not when the test plan ended.

### CODE REVIEW

**Comment by sandromario** [comment]
@aliesbelik Could you help us get this reviewed & merged, please (I'm taking over for t-h-e this week)? Apparently the SonarCloud check failed for some reason. Thanks!

**Review by aliesbelik — COMMENTED** [review]
Backport fix from already merged #11.

**Comment by aliesbelik** [comment]
@sandromario Sorry for delay and thank you for patience.
Sonarcloud failures seem to be irrelevant to changes, will try to investigate (and fix) separately.

**Comment by aliesbelik** [comment]
@t-h-e Thanks!

**Pull request merged**
